version: '3.8'

services:
  api:
    container_name: url-shortener-api
    build:
      context: ../../
      dockerfile: docker/development/Dockerfile
      target: development
    volumes:
      - ../../:/usr/src/app
      - /usr/src/app/node_modules
    ports:
      - ${PORT}:${PORT}
    command: npm run start:dev
    env_file:
      - ../../.env
    networks:
      - url-shortener-network
    depends_on:
      - postgres

  postgres:
    container_name: url-shortener-db
    image: postgres:14-alpine
    networks:
      - url-shortener-network
    environment:
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_DATABASE}
      PG_DATA: /var/lib/postgresql/data
    ports:
      - ${DB_PORT}:5432
    volumes:
      - pgdata:/var/lib/postgresql/data

networks:
  url-shortener-network:

volumes:
  pgdata: