version: '3.8'

services:
  api:
    container_name: url-shortener-api
    build:
      context: .
      target: production
      dockerfile: Dockerfile
    ports:
      - "${PORT:-3000}:3000"
    environment:
      - NODE_ENV=production
      - DB_HOST=postgres
      - DB_PORT=5432
      - DB_USERNAME=${DB_USERNAME}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_DATABASE=${DB_DATABASE}
      - JWT_SECRET=${JWT_SECRET}
      - URL_PREFIX=${URL_PREFIX}
    depends_on:
      - postgres
    networks:
      - url-shortener-network
    restart: always

  postgres:
    container_name: url-shortener-db
    image: postgres:14-alpine
    environment:
      - POSTGRES_USER=${DB_USERNAME}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_DATABASE}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - url-shortener-network
    restart: always

networks:
  url-shortener-network:
    driver: bridge

volumes:
  postgres_data: