global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'url-shortener'
    static_configs:
      - targets: ['api:3000']
    metrics_path: '/api/health/metrics'
    scrape_interval: 5s